/*
CREATE VIEW StudentPairs AS
SELECT DISTINCT E1.SID AS SID1, E2.SID AS SID2
FROM Enrollments E1
JOIN ENROLLMENTS E2 ON E1.sid < E2.sid
LEFT JOIN MEMBERS M1 ON M1.sid = S1.sid
LEFT JOIN MEMBERS M2 ON M2.sid = S2.sid
WHERE E1.cid = E2.cid 
    AND ((M1.pid <> M2.pid) OR (M1.pid = NULL AND M2.pid = NULL));
    */ 

CREATE VIEW StudentPairs AS 
SELECT DISTINCT E1.SID AS SID1, E2.SID AS SID2
FROM Enrollments E1
JOIN ENROLLMENTS E2 ON E1.cid = E2.cid
WHERE E1.sid < E2.sid
MINUS 
SELECT M1.SID, M2.SID
FROM MEMBERS M1
JOIN MEMBERS M2 ON M1.pid = M2.pid;
