SELECT DISTINCT S.sid, S.name
FROM STUDENTS S
JOIN MEMBERS M1 ON M1.sid = S.sid
JOIN MEMBERS M2 ON M2.pid = M1.pid AND M1.sid <> M2.sid
JOIN ENROLLMENTS E1 ON E1.sid = M2.sid 
JOIN COURSES C1 on C1.cid = E1.cid
JOIN ENROLLMENTS E2 on E2.sid = M2.sid 
JOIN COURSES C2 on C2.cid = E2.cid
JOIN ENROLLMENTS E3 on E3.sid = M2.sid
JOIN COURSES C3 on C3.cid = E3.cid
WHERE C1.C_name IN ('EECS482', 'EECS483') AND C2.C_name IN ('EECS484', 'EECS485') AND C3.C_name = 'EECS280'
ORDER BY S.name DESC; 