-- FOLLOW ORDERING
-- 05/11 3rd
-- EVENT LEFT JOIN CITIES
CREATE VIEW VIEW_USER_INFORMATION AS
SELECT UR.USER_ID, UR.FIRST_NAME, UR.LAST_NAME, UR.YEAR_OF_BIRTH, UR.MONTH_OF_BIRTH, UR.DAY_OF_BIRTH, UR.GENDER,
       CUR.CITY_NAME AS CURRENT_CITY, CUR.STATE_NAME AS CURRENT_STATE, CUR.COUNTRY_NAME AS CURRENT_COUNTRY, 
       HOM.CITY_NAME AS HOMETOWN_CITY, HOM.STATE_NAME AS HOMETOWN_STATE, HOM.COUNTRY_NAME AS HOMETOWN_COUNTRY,
       PROG.INSTITUTION AS INSTITUTION_NAME, EDUCATION.PROGRAM_YEAR AS PROGRAM_YEAR, PROG.CONCENTRATION AS PROGRAM_CONCENTRATION, 
       PROG.DEGREE AS PROGRAM_DEGREE
FROM USERS UR
LEFT JOIN USER_CURRENT_CITIES   ON UR.USER_ID = USER_CURRENT_CITIES.USER_ID
LEFT JOIN USER_HOMETOWN_CITIES  ON UR.USER_ID = USER_HOMETOWN_CITIES.USER_ID
LEFT JOIN CITIES CUR            ON USER_CURRENT_CITIES.CURRENT_CITY_ID = CUR.CITY_ID
LEFT JOIN CITIES HOM            ON USER_HOMETOWN_CITIES.HOMETOWN_CITY_ID = HOM.CITY_ID
LEFT JOIN EDUCATION             ON UR.USER_ID = EDUCATION.USER_ID
LEFT JOIN PROGRAMS PROG         ON EDUCATION.PROGRAM_ID = PROG.PROGRAM_ID;

CREATE VIEW VIEW_PHOTO_INFORMATION AS SELECT
    ALB.ALBUM_ID,ALB.ALBUM_OWNER_ID AS OWNER_ID,ALB.COVER_PHOTO_ID,ALB.ALBUM_NAME,ALB.ALBUM_CREATED_TIME,ALB.ALBUM_MODIFIED_TIME,
    ALB.ALBUM_LINK,ALB.ALBUM_VISIBILITY,
    PHO.PHOTO_ID,PHO.PHOTO_CAPTION,PHO.PHOTO_CREATED_TIME,PHO.PHOTO_MODIFIED_TIME,PHO.PHOTO_LINK
FROM 
    (SELECT * FROM ALBUMS) ALB
LEFT JOIN 
    (SELECT * FROM PHOTOS) PHO
ON ALB.ALBUM_ID = PHO.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS SELECT
    EV.EVENT_ID,EV.EVENT_CREATOR_ID,EV.EVENT_NAME,EV.EVENT_TAGLINE,EV.EVENT_DESCRIPTION,EV.EVENT_HOST,
    EV.EVENT_TYPE,EV.EVENT_SUBTYPE,EV.EVENT_ADDRESS,
    CIT.CITY_NAME AS EVENT_CITY,CIT.STATE_NAME AS EVENT_STATE,CIT.COUNTRY_NAME AS EVENT_COUNTRY,
    EV.EVENT_START_TIME,EV.EVENT_END_TIME
FROM 
    (SELECT * FROM USER_EVENTS) EV
LEFT JOIN 
    (SELECT * FROM CITIES) CIT
ON EV.EVENT_CITY_ID = CIT.CITY_ID;

CREATE VIEW VIEW_ARE_FRIENDS AS SELECT * FROM FRIENDS;
CREATE VIEW VIEW_TAG_INFORMATION AS SELECT * FROM TAGS;