DROP TABLE TAGS;
DROP TABLE FRIENDS;
DROP TABLE MESSAGES;
DROP TABLE EDUCATION;
DROP TABLE PROGRAMS;

DROP TABLE PARTICIPANTS;
DROP TABLE USER_EVENTS;
DROP TABLE USER_HOMETOWN_CITIES; 
DROP TABLE USER_CURRENT_CITIES;
DROP TABLE CITIES;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE ALBUMS CASCADE CONSTRAINTS;
DROP TABLE PHOTOS CASCADE CONSTRAINTS;

DROP SEQUENCE CITY_SEQ_2;
DROP SEQUENCE PROG_SEQ_2;